### ISSUE TITLE
Unable to login to Streamlit app for data verification

### ISSUE THREAD

**Issue by LakshyaSharma2025** [SixthSensAIOrg/Techpack_streamlit#1]
![Screenshot 2024-10-14 092251](https://github.com/user-attachments/assets/b1b038bf-cab3-4916-b358-4bc6e5745c64)

Dear SixthSens Team,

I am currently in the process of validating data as requested to calculate overall accuracy , however i am unable to open the streamlit server as shown in the attached picture. Please let me know if it is corrected or the solution from my side if possible.

Regards,
Lakshya Sharma
World Fashion Exchange

**Comment by n-rane** [comment]
Hi Lakshya, Please use the new link below to access the app:

https://techpack2.streamlit.app/
